//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.29 at 10:42:16 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hello.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.xml.jaxbLesson;
