package edu.xml.jaxbLesson;
import java.io.*;
import java.util.*;
import javax.xml.bind.*;
// import java content classes generated by binding compiler
//import com.mybank.schema.*;


public class ReadWritePO
{
	public static void main( String[] args ) throws Exception
	{
		m2();
	}
	private static void m1() throws Exception
	{
		JAXBContext context =JAXBContext.newInstance( "lesson2.xml.jaxbLesson" );
		Unmarshaller unmars = context.createUnmarshaller();
		Purchaseorder po = (Purchaseorder)
      	unmars.unmarshal(
			new FileInputStream( "C:\\temp\\xml\\xsd\\purchaseorder.xml" ) );
  		Billingaddress address = po.getBillingaddress();
		String name= address.getName();
		String street= address.getStreet();
		String   city= address.getCity();
		String state = address.getState();
		int zip= address.getZip();
		System.out.println( "Billing address in the XML is : " );
		System.out.println("Name :" + name);
 		System.out.println("Street :" + street);
		System.out.println("City :" + city);
		System.out.println("State :" + state);
		System.out.println("Zip :" + zip);

		Items order=po.getItems();
		Iterator it=order.getItem().iterator();
		while(it.hasNext()){
				Item item=	(Item)it.next();
				System.out.println("Order contains" );
				System.out.println("	Description: " + item.getDescription());
				System.out.println("	Product number: " + item.getProductnumber());
				System.out.println("	Quantity: " + item.getQuantity());
				System.out.println("	Unit cost: " + item.getUnitcost());
		}
		// 	Change some information
		address.setName("Venkat Krishnan");
		address.setZip(900011);

		Marshaller mars = context.createMarshaller();
		mars.setProperty(
			Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE );

		mars.setProperty (
			Marshaller.JAXB_SCHEMA_LOCATION,"http://www.hello.com purchaseorder.xsd");

		mars.marshal( po, new FileOutputStream("C:\\temp\\xml\\xsd\\po.xml"));
	}
	private static void m2()
	{
		 try {
			 JAXBContext jaxbContext = JAXBContext.newInstance(Purchaseorder.class);
			 Unmarshaller unmars = jaxbContext.createUnmarshaller();
			 Purchaseorder po = (Purchaseorder)
		     unmars.unmarshal(
					new FileInputStream( "C:\\temp\\xml\\xsd\\purchaseorder.xml" ) );
		  		Billingaddress address = po.getBillingaddress();
				String name= address.getName();
				String street= address.getStreet();
				String   city= address.getCity();
				String state = address.getState();
				int zip= address.getZip();
				System.out.println( "Billing address in the XML is : " );
				System.out.println("Name :" + name);
		 		System.out.println("Street :" + street);
				System.out.println("City :" + city);
				System.out.println("State :" + state);
				System.out.println("Zip :" + zip);

				Items order=po.getItems();
				Iterator it=order.getItem().iterator();
				while(it.hasNext()){
						Item item=	(Item)it.next();
						System.out.println("Order contains" );
						System.out.println("	Description: " + item.getDescription());
						System.out.println("	Product number: " + item.getProductnumber());
						System.out.println("	Quantity: " + item.getQuantity());
						System.out.println("	Unit cost: " + item.getUnitcost());
				}
				// 	Change some information
				address.setName("Venkat Krishnan");
				address.setZip(900011);


				File file = new File("C:\\temp\\xml\\jaxb\\pofile.xml");
//				JAXBContext jaxbContext = JAXBContext.newInstance(Purchaseorder.class);
				Marshaller jaxbMarshaller = jaxbContext.createMarshaller();

				// output pretty printed
				jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);

				jaxbMarshaller.marshal(po, file);
				jaxbMarshaller.marshal(po, System.out);

			} catch (JAXBException e) {
				e.printStackTrace();
			}catch (Exception e) {
				e.printStackTrace();
			}
		
	}
}